# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [published]

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup Node
      - name: Install node
        uses: actions/setup-node@v2

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Publish
        run: |
          echo ${{ github.event.release.tag_name }}
          gt show-ref
          git config --global user.name 'lounge1k'
          git config --global user.email 'lounge1k@gmail.com'
          git add -f build
          git commit -m "new release ${{ github.event.release.tag_name }}"
          git push -f origin `git subtree split --prefix build master`:gh-pages

